version: '3.7'
services:

  socks5:
    image: serjs/go-socks5-proxy
    container_name: socks5
    restart: always
    env_file:
      - .env
    ports:
      - 1080:1080
    networks:
      - backend
  influx:
    image: influxdb:1.8-alpine
    container_name: influx
    restart: always
    env_file:
      - .env
    networks:
      - backend
    ports:
      - 8086:8086
    volumes:
      - ./data/influx:/var/lib/influxdb
    depends_on:
      - telegraf

  telegraf:
    image: telegraf:alpine
    container_name: telegraf
    restart: always
    environment:
      HOST_PROC: /rootfs/proc
      HOST_SYS: /rootfs/sys
      HOST_ETC: /rootfs/etc
    networks:
      - backend
    volumes:
      - ./conf/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys:/rootfs/sys:ro
      - /proc:/rootfs/proc:ro
      - /etc:/rootfs/etc:ro

  
networks:
  backend:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.16.0/24